<?php 

function thb_get_testimonials_templates($template_list) {
	$template_list['testimonials_section_01'] = array(
		'name' => esc_html__( 'Testimonials Section - 01', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e1.jpg",
		'cat' => array( 'testimonials', 'about' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1517400857178{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="142"][/thb_image][vc_empty_space height="46px"][vc_column_text animation="animation bottom-to-top" el_class="text-center"]
		<h2>What People Are Saying</h2>
		[/vc_column_text][vc_empty_space height="60px"][thb_testimonial_parent thb_style="style3" columns="medium-4"][thb_testimonial thb_review="true" thb_review_stars="4" quote_title="Most informative tour that I’ve ever taken" quote="I booked my trip package from andaman great holidays for five people 14 to 19 March 2018, and I am fully satisfied with the information shared by them and they took good care of our requirements in terms of hotels and sightseeing." author_name="Lauren White" author_title="Casual hiker"][thb_testimonial thb_review="true" quote_title="Well organized tour" quote="The trip was very well organised and executed. The drivers were very professional and punctual throughout the trip. We were able to manage throughout the trip without knowing hindi/local language as hotel staff/drivers/tour operators were able to communicate in English." author_name="Lauren White" author_title="Casual hiker"][thb_testimonial thb_review="true" quote_title="We had a wonderful time in Cuba" quote="My overall experience was good as it was the first entire family trip of mine.. Hotels cab n driver n Also the agent priya from holiday triangle helped in making it an unforgettable.. Few glitch happened like miscommunication in the kochi hotel regarding booking." author_name="Lauren White" author_title="Casual hiker"][thb_testimonial thb_review="true" quote_title="What a wonderful experience!" quote="Cab driver is very helpful to visit the places &amp; relocate to hotels Munnar hill gats, alleppy house boat &amp; back water, kovalm beaches &amp; poover golden beach with morgen trees align with back water, kanyakumari Holly place." author_name="Lauren White" author_title="Casual hiker"][thb_testimonial thb_review="true" thb_review_stars="3" quote_title="I am looking for my E-ticket" quote="Our trip was 14 march to 19 march I got many quotes but i decided to go with Holiday planners. I visited port blair havelock island neil island. It was an awesome memorable trip. Team holiday planner u were rocking guys." author_name="Lauren White" author_title="Casual hiker"][thb_testimonial thb_review="true" thb_review_stars="3" quote_title="Four friends on an adventure" quote="I am not happy with the services offered to me. Completely dissatisfied. There were number of things missing and not offered to me. Tour and trips was also missing. They didnt even offered activities, flight veg food." author_name="Lauren White" author_title="Casual hiker"][/thb_testimonial_parent][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_02'] = array(
		'name' => esc_html__( 'Testimonials Section - 02', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e2.jpg",
		'cat' => array( 'testimonials', 'about', 'cta' ),
		'sc' => '[vc_row thb_full_width="true" css=".vc_custom_1517393148944{padding-bottom: 30vh !important;background-image: url(http://revolution.fuelthemes.net/revolution-adventure/wp-content/uploads/sites/2/2018/01/a4.jpg?id=127) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column el_class="text-center"][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-7 vc_col-md-10"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="119"][/thb_image][vc_empty_space height="60px"][vc_column_text animation="animation bottom-to-top-3d"]
		<h2><strong><span style="color: #db703b;">“Broad, wholesome, charitable views of men and things cannot be acquired by vegetating in one little corner of the earth all of one’s lifetime.”</span></strong></h2>
		[/vc_column_text][vc_empty_space height="40px"][thb_button animation="animation bottom-to-top" size="x-large" color="gradient" border_radius="pill-radius" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Plan%20Your%20Visit|target:%20_blank|" bg_gradient1="rgba(27,226,149,0.59)" bg_gradient2="#1be295" st_color="#1be295"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_03'] = array(
		'name' => esc_html__( 'Testimonials Section - 03', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e3.jpg",
		'cat' => array( 'testimonials', 'about' ),
		'sc' => '[vc_row thb_full_width="true" css=".vc_custom_1519210600870{padding-top: 14vh !important;padding-bottom: 14vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/test_bg.png?id=122) !important;background-position: 0 0 !important;background-repeat: repeat !important;}" el_class="dot-pattern-bg"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-8 vc_col-md-9"][thb_testimonial_parent thb_style="style2" autoplay="true"][thb_testimonial quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aoron Walter"][thb_testimonial quote="“Great theme with a clean, flexible and modular design. The theme is very well integrated with Visual Composer which makes it a breeze to use and configure.”" author_name="Jason Bourne"][thb_testimonial quote="“Over the past 10 years I have installed and configured over 50 websites. This ``Revolution`` theme is the best theme I have ever purchased.”" author_name="Michael Walters"][/thb_testimonial_parent][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_04'] = array(
		'name' => esc_html__( 'Testimonials Section - 04', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e4.jpg",
		'cat' => array( 'testimonials', 'about' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" parallax="content-moving" css=".vc_custom_1520854271850{margin-top: 15vh !important;padding-top: 20vh !important;padding-bottom: 20vh !important;background-image: url(http://revolution.fuelthemes.net/revolution-adventure/wp-content/uploads/sites/2/2018/02/a44.jpg?id=197) !important;background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner thb_color="thb-light-column" offset="vc_col-lg-8 vc_col-md-10"][thb_testimonial_parent thb_style="style2"][thb_testimonial quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aoron Walter" author_title="Senior Product Designer at Uber"][thb_testimonial quote="“Takes a little effort to get it structured the way you want it but I love the way it looks. Fabulous looking theme and good support from developer. ”" author_name="Jason Bourne Walter" author_title="CTO at Uber"][thb_testimonial quote="“Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Ant Eksiler" author_title="CFO at Fuel Themes"][/thb_testimonial_parent][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_06'] = array(
		'name' => esc_html__( 'Testimonials Section - 06', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e6.jpg",
		'cat' => array( 'testimonials', 'about' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" content_placement="middle"][vc_column thb_color="thb-light-column" width="1/2" css=".vc_custom_1521198731120{padding-top: 10% !important;padding-right: 12% !important;padding-bottom: 10% !important;padding-left: 12% !important;background-color: #beddd8 !important;}"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="152"][/thb_image][vc_empty_space height="42px"][thb_testimonial_parent thb_style="style2"][thb_testimonial quote="“Fabulous looking theme and good support developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aaron Walter"][thb_testimonial quote="“This theme is easy to use and offers a lot of possibilities. The customer support answer quickly and accurately. Nothing bad to say!”" author_name="Speed Aperture"][thb_testimonial quote="“So far so good. I have no previous experience regarding Wordpress Themes, but I seem to be finding my way.”" author_name="Albers Mayo"][/thb_testimonial_parent][/vc_column][vc_column width="1/2" css=".vc_custom_1519069926418{padding-top: 30% !important;padding-right: 30% !important;padding-bottom: 30% !important;padding-left: 30% !important;background-image: url(http://revolution.fuelthemes.net/revolution-classic/wp-content/uploads/sites/8/2018/02/c8.jpg?id=151) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="text-center"][thb_video_lightbox icon_style="style3" animation="animation fade-in" video="https://vimeo.com/252767901" icon_color="#ffffff"][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_07'] = array(
		'name' => esc_html__( 'Testimonials Section - 07', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e7.jpg",
		'cat' => array( 'testimonials' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1517304266270{padding-top: 15vh !important;padding-bottom: 15vh !important;background-color: #fdfaf7 !important;}"][vc_column][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="141"][/thb_image][vc_empty_space height="46px"][vc_column_text animation="animation bottom-to-top" el_class="text-center"]
		<h2>Where To Eat</h2>
		[/vc_column_text][vc_empty_space height="60px"][vc_row_inner][vc_column_inner][thb_testimonial_parent thb_style="style5"][thb_testimonial thb_review="true" thb_review_stars="4" quote_title="La Degustation Bohême Bourgeoise" quote="On a romantic back street in Old Town, this culinary shrine won one of the Czech Republic’s three Michelin stars for its unique style of parading precious locally sourced courses to the table, ranging from snails with leek to carp in almonds and boar nestled in juniper." review_image="179" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Frevolution-adventure%2Fabout-us%2F|||"][thb_testimonial thb_review="true" quote_title="Sad Mans Tongue Bar &amp; Bistro" quote="Great service and a great menu. The donut onion rings are amazing!! you get a lot of food so dont make the mistake like us and order too much! Burgers are very large!!
		Cheap good food and drinks!! " review_image="180" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Frevolution-adventure%2Fabout-us%2F|||"][thb_testimonial thb_review="true" thb_review_stars="3" quote_title="Potrefena Husa Na Verandach" quote="The food was high quality, had svickova and smazak (fried cheese) - good portion sizes. Also the staff was very friendly and knowledgable. We live locally and will come again. A lot better experience than in the other Potrefena Husa - which is close to Andel metro station." review_image="181" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Frevolution-adventure%2Fabout-us%2F|||"][/thb_testimonial_parent][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_08'] = array(
		'name' => esc_html__( 'Testimonials Section - 08', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e8.jpg",
		'cat' => array( 'testimonials', 'about' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1520251143411{padding-top: 15vh !important;padding-bottom: 15vh !important;background: #f4ebeb url(http://revolution.fuelthemes.net/revolution-agency-creative/wp-content/uploads/sites/13/2018/03/testimonials_bg.jpg?id=181) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-8 vc_col-md-9"][vc_column_text]
		<h5>Testimonials</h5>
		[/vc_column_text][thb_testimonial_parent][thb_testimonial quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aoron Walter" author_title="Senior Product Designer at Uber" author_image="145"][thb_testimonial quote="“This theme is easy to use and offers a lot of possibilities. The customer support answer quickly and accurately. Nothing bad to say!”" author_name="Kimmy Gulotta" author_title="Creative Director at Crux" author_image="141"][thb_testimonial quote="“Works great and it is easy to setup. Great choice for plenty of different styles. Had no issues so far. Support works also well if you need it. Thanks.”" author_name="Brad Garling" author_title="CEO at Ripple Inc." author_image="150"][/thb_testimonial_parent][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['testimonials_section_09'] = array(
		'name' => esc_html__( 'Testimonials Section - 09', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/testimonials/testimonials-e9.jpg",
		'cat' => array( 'testimonials' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" parallax="content-moving" css=".vc_custom_1523029206662{padding-top: 20vh !important;padding-bottom: 18vh !important;background-image: url(http://revolution.fuelthemes.net/revolution-corporate-agency/wp-content/uploads/sites/5/2018/04/bg_t.jpg?id=341) !important;background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner el_class="align-center" css=".vc_custom_1523018702485{margin-bottom: 50px !important;}"][vc_column_inner thb_color="thb-light-column" el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_slidetype slide_text="
		<h6><strong>*WHAT OUR CLIENTS SAY ABOUT US*</strong></h6>
		"][vc_empty_space height="20px"][vc_column_text animation="animation fade-in"]Here’s a cross section of what our customers across a number of different industries have to say…[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="align-center"][vc_column_inner thb_color="thb-light-column" offset="vc_col-lg-10 vc_col-md-11"][thb_testimonial_parent thb_style="style6" columns="medium-6" autoplay="true"][thb_testimonial quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="XRP Hodler" author_title="Senior Developer at Ripple" author_image="257"][thb_testimonial quote="“Awesome theme, still going strong with new updates and features -- our clients love the options! Great updates and support as well.”" author_name="Kimmy Gulotta" author_title="Game Designer at Ubisoft" author_image="256" review_image="119"][thb_testimonial quote="“Great theme and support. Clean modern design with lots of customizability built-in. All best practices are in place for theme backend options..”" author_name="Thomas Shelby" author_title="Web Designer at Invictus" author_image="255"][thb_testimonial quote="“Flexible, but some obvious tweaks are not possible without diving into CSS. Good support team will help you.”" author_name="Grad Darling" author_title="Web Designer at Ripple" author_image="254"][/thb_testimonial_parent][/vc_column_inner][/vc_row_inner][vc_empty_space height="42px"][vc_row_inner el_class="align-center"][vc_column_inner thb_color="thb-light-column" el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_button animation="animation bottom-to-top" size="small" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Frevolution-corporate-agency%2Fservices%2F|title:View%20All%20Reviews||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	return $template_list;
}