<?php 

function thb_get_clients_templates($template_list) {
	$template_list['clients_section_01'] = array(
		'name' => esc_html__( 'Clients Section - 01', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/clients/clients-e1.jpg",
		'cat' => array( 'clients', 'about' ),
		'sc' => '[vc_row][vc_column width="1/2"][thb_slidetype slide_text="
		<h6>*SELECTED CLIENTS*</h6>
		" thb_animated_color="#343434" extra_class="small-heading"][vc_empty_space height="30px"][/vc_column][vc_column width="1/2"][/vc_column][/vc_row][vc_row][vc_column][thb_clients_parent thb_columns="small-6 large-3" animation="animation fade-in"][thb_clients image="84" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="85" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="86" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="87" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="88" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="89" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="90" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][thb_clients image="91" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Client||"][/thb_clients_parent][vc_empty_space height="120px"][/vc_column][/vc_row]',
	);
	$template_list['clients_section_02'] = array(
		'name' => esc_html__( 'Clients Section - 02', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/clients/clients-e2.jpg",
		'cat' => array( 'clients', 'about' ),
		'sc' => '[vc_row el_class="text-center align-center" css=".vc_custom_1516357743337{padding-top: 14vh !important;padding-bottom: 6vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-9"][thb_slidetype slide_text="
		<h2>*Awards*</h2>
		"][vc_column_text animation="animation bottom-to-top"]<span style="color: #91959c;">Yielding fowl their brought is own day place fruit creature our day lesser cant bring hath after. Divide there forth fruitful.</span>[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column width="5/6"][vc_row_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="148" icon_image_width="150" thb_heading_color="#91959c" counter="18" heading="The Webby Awards"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="149" icon_image_width="150" thb_heading_color="#91959c" counter="6" heading="Awwwards"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="150" icon_image_width="150" thb_heading_color="#91959c" counter="14" heading="Fwa"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="151" icon_image_width="150" thb_heading_color="#91959c" counter="3" heading="Css Design Awards"][/vc_column_inner][/vc_row_inner][vc_empty_space height="60px"][vc_row_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="152" icon_image_width="150" thb_heading_color="#91959c" counter="4" heading="Creative Review"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="153" icon_image_width="150" thb_heading_color="#91959c" counter="10" heading="Cannes Lions"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="159" icon_image_width="150" thb_heading_color="#91959c" counter="9" heading="The Communicator"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="160" icon_image_width="150" thb_heading_color="#91959c" counter="5" heading="Css Light"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['clients_section_03'] = array(
		'name' => esc_html__( 'Clients Section - 03', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/clients/clients-e3.jpg",
		'cat' => array( 'clients', 'about' ),
		'sc' => '[vc_row][vc_column][vc_row_inner thb_max_width=""][vc_column_inner width="1/2"][vc_column_text]
		<h5>Selected Clients</h5>
		[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][/vc_column_inner][/vc_row_inner][vc_row_inner thb_max_width="" css=".vc_custom_1520255476870{padding-top: 6vh !important;}"][vc_column_inner width="1/4"][thb_iconbox heading="Ben Pfaffle" icon_image="160" icon_image_width="100" icon_image_hover="161"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Carola Petri" icon_image="159" icon_image_width="100" icon_image_hover="158"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Gennusschemelzerei" icon_image="162" icon_image_width="150" icon_image_hover="163"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Otto’s Burger" icon_image="165" icon_image_width="100" icon_image_hover="164"][/vc_column_inner][/vc_row_inner][vc_row_inner thb_max_width="" css=".vc_custom_1520255515785{padding-top: 4vh !important;padding-bottom: 10vh !important;}"][vc_column_inner width="1/4"][thb_iconbox heading="Bring The Noise" icon_image="167" icon_image_width="100" icon_image_hover="166"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Bleckmar" icon_image="168" icon_image_width="110" icon_image_hover="169"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Reykjavik Fashion" icon_image="176" icon_image_width="100" icon_image_hover="177"][/vc_column_inner][vc_column_inner width="1/4"][thb_iconbox heading="Catwork Design" icon_image="175" icon_image_width="100" icon_image_hover="174"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['clients_section_04'] = array(
		'name' => esc_html__( 'Clients Section - 04', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/clients/clients-e4.jpg",
		'cat' => array( 'clients', 'about' ),
		'sc' => '[vc_row css=".vc_custom_1519399321372{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column][thb_slidetype slide_text="
		<h6>*Trusted Clients*</h6>
		" thb_animated_color="rgba(33,51,100,0.6)"][vc_empty_space height="60px"][thb_slidetype slide_text="
		<h2>*We are pleased to have many;trusted partners.*</h2>
		" thb_animated_color="#213364"][vc_empty_space height="60px"][thb_clients_parent thb_columns="small-6 large-3" animation="animation fade-in" thb_image_borders="true" thb_hover_effect="thb-opacity"][thb_clients image="198"][thb_clients image="197"][thb_clients image="196"][thb_clients image="195"][thb_clients image="194"][thb_clients image="192"][thb_clients image="193"][thb_clients image="191"][/thb_clients_parent][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1519378612050{padding-top: 20vh !important;padding-bottom: 20vh !important;background: #fef5ba url(http://revolution.fuelthemes.net/revolution-consulting/wp-content/uploads/sites/9/2018/02/h11.jpg?id=147) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="8" heading="Years of Experiences" icon_image="171" icon_image_width="36"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="63" heading="Countries Served" icon_image="172" icon_image_width="46"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="40" heading="Hardworking Peoples" icon_image="173" icon_image_width="36"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="5" heading="Offices Worldwide" icon_image="174" icon_image_width="40"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	return $template_list;
}