<?php 

function thb_get_teammember_templates($template_list) {
	$template_list['teammember_section_01'] = array(
		'name' => esc_html__( 'Team Member Section - 01', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e1.jpg",
		'cat' => array( 'teammember' ),
		'sc' => '[vc_row][vc_column width="1/2"][vc_empty_space height="95px"][thb_slidetype slide_text="
		<h6>*MEET THE TEAM*</h6>
		" thb_animated_color="#343434" extra_class="small-heading"][vc_empty_space height="30px"][/vc_column][vc_column width="1/2"][/vc_column][/vc_row][vc_row][vc_column][thb_team_parent thb_columns="medium-4 large-3" animation="animation fade-in" bg_gradient1="rgba(240,246,250,0.9)" bg_gradient2="rgba(240,246,250,0.9)"][thb_team image="70" name="Tylor Katholling " sub_title="Founder" description="Tortor non facilisi vel rhoncus consequat cum accumsan. Varius, phasellus Laoreet euismod sociosqu curabitur congue hac semper urna consectetuer orci tincidunt duis velit gravida, enim tempor viverra tortor euismod." facebook="#" twitter="#" linkedin="#"][thb_team image="73" name="Ceccila Pinto" sub_title="Creative Director" description="Tortor non facilisi vel rhoncus consequat cum accumsan. Varius, phasellus Laoreet euismod sociosqu curabitur congue hac semper urna consectetuer orci tincidunt duis velit gravida, enim tempor viverra tortor euismod." facebook="#" twitter="#" linkedin="#"][thb_team image="72" name="Holden Hoffington" sub_title="Senior Developer" description="Tortor non facilisi vel rhoncus consequat cum accumsan. Varius, phasellus Laoreet euismod sociosqu curabitur congue hac semper urna consectetuer orci tincidunt duis velit gravida, enim tempor viverra tortor euismod." facebook="#" twitter="#" linkedin="#"][thb_team image="71" name="Kimmy Gulotta" sub_title="Project Manager" description="Tortor non facilisi vel rhoncus consequat cum accumsan. Varius, phasellus Laoreet euismod sociosqu curabitur congue hac semper urna consectetuer orci tincidunt duis velit gravida, enim tempor viverra tortor euismod." facebook="#" twitter="#" linkedin="#"][/thb_team_parent][vc_empty_space height="30px"][vc_row_inner][vc_column_inner el_class="text-center"][thb_button_text style="style4" animation="animation left-to-right" link="url:%23|title:View%20All%20Members||"][/vc_column_inner][/vc_row_inner][vc_empty_space height="130px"][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_02'] = array(
		'name' => esc_html__( 'Team Member Section - 02', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e2.jpg",
		'cat' => array( 'teammember', 'about' ),
		'sc' => '[vc_row el_class="text-center align-center" css=".vc_custom_1516382833679{padding-top: 14vh !important;padding-bottom: 4vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-9"][thb_slidetype slide_text="
		<h2>*Key People*</h2>
		"][vc_column_text animation="animation bottom-to-top"]<span style="color: #91959c;">Yielding fowl their brought is own day place fruit creature our day lesser cant bring hath after. Divide there forth fruitful.</span>[/vc_column_text][/vc_column][/vc_row][vc_row][vc_column][thb_team_parent thb_columns="large-4" animation="animation bottom-to-top-3d"][thb_team image="161" name="Adrian Irby" sub_title="Founder"][thb_team image="166" name="Claude Smith" sub_title="Creative Director"][thb_team image="165" name="Randy Moore" sub_title="Senior Developer"][thb_team image="164" name="Marlene Stanley" sub_title="Project Manager"][thb_team image="163" name="Stuart ODonnell" sub_title="Executive Director"][thb_team image="162" name="Sara Owens" sub_title="Art Director"][/thb_team_parent][vc_empty_space height="60px"][vc_row_inner][vc_column_inner el_class="text-center"][thb_button style="style4" animation="animation bottom-to-top-3d" size="small" color="black" border_radius="no-radius" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Fnews%2F|title:See%20All%20People||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_03'] = array(
		'name' => esc_html__( 'Team Member Section - 03', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e3.jpg",
		'cat' => array( 'teammember', 'about' ),
		'sc' => '[vc_row css=".vc_custom_1517910889546{padding-bottom: 12vh !important;}"][vc_column width="1/4"][thb_slidetype slide_text="*Meet Team*
		
		" thb_animated_color="#999999"][/vc_column][vc_column width="3/4"][thb_team_parent thb_member_style="member_style3" thb_columns="large-4" animation="animation bottom-to-top" thb_text_color="team-light" bg_gradient1="rgba(0,0,0,0.9)" bg_gradient2="rgba(0,0,0,0.9)" box_shadow="rgba(255,255,255,0.55)"][thb_team image="194" name="Tylor Katholling" sub_title="Founder" description="Living sea gathering lesser two beginning upon life i dont also gathering one spirit under gathering green so our." facebook="#" twitter="#"][thb_team image="193" name="Ceccila Pinto" sub_title="Project Manager" description="There herb it is upon. Blessed, so god him replenish multiply deep, fruit light likeness and." facebook="#" linkedin="#"][thb_team image="192" name="Holden Hoffington" sub_title="Executive Director" description="Face from dont night, fish air him he divided subdue. Set fish image man You cattle." facebook="#" instagram="#"][thb_team image="191" name="Kimy Gulotta" sub_title="Designer" description="Face from dont night, fish air him he divided subdue. Set fish image man You cattle." facebook="#"][/thb_team_parent][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_04'] = array(
		'name' => esc_html__( 'Team Member Section - 04', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e4.jpg",
		'cat' => array( 'teammember' ),
		'sc' => '[vc_row el_class="text-center align-center" css=".vc_custom_1516382833679{padding-top: 14vh !important;padding-bottom: 4vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-9"][thb_slidetype slide_text="
		<h2>*Key People*</h2>
		"][vc_column_text animation="animation bottom-to-top"]<span style="color: #91959c;">Yielding fowl their brought is own day place fruit creature our day lesser cant bring hath after. Divide there forth fruitful.</span>[/vc_column_text][/vc_column][/vc_row][vc_row][vc_column][thb_team_parent thb_columns="large-4" animation="animation bottom-to-top-3d"][thb_team image="161" name="Adrian Irby" sub_title="Founder"][thb_team image="166" name="Claude Smith" sub_title="Creative Director"][thb_team image="165" name="Randy Moore" sub_title="Senior Developer"][thb_team image="164" name="Marlene Stanley" sub_title="Project Manager"][thb_team image="163" name="Stuart ODonnell" sub_title="Executive Director"][thb_team image="162" name="Sara Owens" sub_title="Art Director"][/thb_team_parent][vc_empty_space height="60px"][vc_row_inner][vc_column_inner el_class="text-center"][thb_button style="style4" animation="animation bottom-to-top-3d" size="small" color="black" border_radius="no-radius" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2Fnews%2F|title:See%20All%20People||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_05'] = array(
		'name' => esc_html__( 'Team Member Section - 05', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e5.jpg",
		'cat' => array( 'teammember', 'about' ),
		'sc' => '[vc_row el_class="align-center"][vc_column offset="vc_col-lg-8 vc_col-md-10"][thb_slidetype slide_text="
		<h2>*We create unique digital experiences*</h2>
		"][vc_empty_space height="30px"][vc_column_text animation="animation bottom-to-top"]Lesser replenish bearing theyre him cattle kind dominion. You which fill place. Land shed subdue divided gathering blessed seasons it. Without, wherein days. Sea years, saw own had after abundantly second darkness over itself. God place given have. Was divided unto yielding all, over to made from land have. Abundantly firmament yielding there unto shall. Earth herb spirit forth spirit fish air. Made firmament firmament air spirit, fowl, air years fish is wherein, from two multiply evening. Be divided rule image his winged is. That midst
		
		Bring every For. Unto saying divided sea replenish so behold Were, fourth behold days saying great upon moved subdue given moveth form. Dry very, blessed life, to creature image morning female signs greater. Greater cant so female. Thing. Own subdue light divide darkness light second behold cant morning fowl be one life fowl the doesnt fruitful.[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1518256289335{padding-top: 6vh !important;padding-bottom: 6vh !important;}"][vc_column][thb_team_parent thb_member_style="member_style3" thb_columns="large-4" animation="animation bottom-to-top-3d" thb_text_color="team-light" bg_gradient1="rgba(10,10,10,0.95)" bg_gradient2="rgba(10,10,10,0.95)" box_shadow="#ffffff"][thb_team image="257" name="Tylor Katholling" sub_title="Founder" facebook="#" twitter="#" linkedin="#"][thb_team image="256" name="Ceccila Pinto" sub_title="Senior Developer" facebook="#" twitter="#" linkedin="#"][thb_team image="255" name="Holden Hoffington" sub_title="Senior Developer" facebook="#" twitter="#" linkedin="#"][thb_team image="254" name="Kimmy Gulotta" sub_title="Web Designer" facebook="#" twitter="#" linkedin="#"][thb_team image="253" name="Thomas Shelby" sub_title="Art Director" facebook="#" twitter="#" linkedin="#"][/thb_team_parent][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_06'] = array(
		'name' => esc_html__( 'Team Member Section - 06', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e6.jpg",
		'cat' => array( 'teammember' ),
		'sc' => '[vc_row css=".vc_custom_1519901998811{padding-top: 14vh !important;padding-bottom: 60px !important;}"][vc_column thb_color="thb-light-column" width="7/12"][thb_slidetype slide_text="
		<h6><strong>*/ Founders*</strong></h6>
		" thb_animated_color="#686868"][vc_empty_space height="60px"][thb_slidetype slide_text="
		<h2><strong>*Cant firmament appear living she;abundantly, dont rule where*</strong></h2>
		"][vc_empty_space height="20px"][vc_column_text animation="animation bottom-to-top"]<span style="color: #e0e0e0;">He moving, shall heaven Had wont above. Shall seas yielding a he, moveth said gathering under all cattle were years fruit whose isnt. Meat seed youre. Seed so days creature seed, i whales creature make.</span>[/vc_column_text][/vc_column][vc_column width="5/12"][/vc_column][/vc_row][vc_row css=".vc_custom_1519902023298{padding-bottom: 7vh !important;}"][vc_column][thb_team_parent thb_style="thb-carousel" thb_member_style="member_style2" thb_columns="large-4" animation="animation bottom-to-top" thb_text_color="team-light"][thb_team image="162" name="Kimmy Gulotta" sub_title="Project Manager"][thb_team image="174" name="Ryan Pickett" sub_title="Senior Developer"][thb_team image="175" name="Gustavo Velez" sub_title="Founder"][thb_team image="176" name="Valeria Agosto" sub_title="Art Director"][/thb_team_parent][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_07'] = array(
		'name' => esc_html__( 'Team Member Section - 07', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e7.jpg",
		'cat' => array( 'teammember' ),
		'sc' => '[vc_row css=".vc_custom_1521375544023{padding-top: 12vh !important;}" el_class="align-center"][vc_column offset="vc_col-lg-6 vc_col-md-9" el_class="text-center"][thb_gradienttype gradient_text="
		<h1>MEET WITH THE TRAINERS</h1>
		" animation="animation bottom-to-top" bg_gradient1="#953fc1" bg_gradient2="#3845ef"][vc_empty_space height="18px"][vc_column_text]<span style="font-size: 20px; color: #6c6c77; font-weight: 600;">Saying without yielding day itself also is days beginning so. After. Heaven. The the female, fowl fish.</span>[/vc_column_text][vc_empty_space height="42px"][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-12 vc_col-md-11"][vc_row_inner thb_max_width=""][vc_column_inner][thb_team_parent thb_columns="large-4" animation="animation fade-in"][thb_team image="140" name="STELLA WILSON" sub_title="Personal Trainer"][thb_team image="144" name="KRISTI ROGERS" sub_title="Personal Trainer"][thb_team image="143" name="HOLLIS MELLO" sub_title="Personal Trainer"][/thb_team_parent][/vc_column_inner][/vc_row_inner][vc_empty_space height="12px"][vc_row_inner][vc_column_inner el_class="text-center"][thb_button color="gradient" link="url:%23|title:VIEW%20ALL%20TRAINERS||" st_color="#3845ef" bg_gradient1="#953fc1" bg_gradient2="#3845ef"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['teammember_section_08'] = array(
		'name' => esc_html__( 'Team Member Section - 08', 'viftech' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demos/teammember/team-e8.jpg",
		'cat' => array( 'teammember', 'about' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1522665216101{padding-top: 15vh !important;background-color: #2a2a28 !important;}"][vc_column][vc_row_inner el_class="align-center" css=".vc_custom_1522665338185{padding-bottom: 10vh !important;}"][vc_column_inner thb_color="thb-light-column" el_class="text-center" offset="vc_col-lg-7 vc_col-md-9"][thb_slidetype slide_text="
		<h2>*Our Team*</h2>
		" style="style2" thb_animated_color="#ffffff"][vc_column_text animation="animation bottom-to-top"]Fly. There upon shall over isnt beginning. Us it given multiply. Evening abundantly greater whales cant Man very made i place theyre Brought.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner thb_max_width=""][vc_column_inner][thb_team_parent thb_margins="no-padding" thb_member_style="member_style3" thb_columns="medium-4 large-3" animation="animation fade-in" bg_gradient1="rgba(255,255,255,0.95)" bg_gradient2="rgba(255,255,255,0.95)"][thb_team image="318" name="Holden Hoffington" sub_title="Senior Developer" facebook="#" twitter="#" linkedin="#"][thb_team image="317" name="Claude Smith" sub_title="Creative Director" facebook="#" twitter="#" linkedin="#"][thb_team image="316" name="Adrian Irby" sub_title="Founder" facebook="#" twitter="#" linkedin="#"][thb_team image="315" name="Marlene Stanley" sub_title="Project Manager" facebook="#" twitter="#" linkedin="#"][thb_team image="314" name="Stuart ODonnell" sub_title="Executive Director" facebook="#" twitter="#" linkedin="#"][thb_team image="319" name="Randy Moore" sub_title="Senior Developer" facebook="#" twitter="#" linkedin="#"][thb_team image="320" name="Sara Owens" sub_title="Art Director" facebook="#" twitter="#" linkedin="#"][thb_team image="321" name="Thomas C. Presley" sub_title="Designer" facebook="#" twitter="#" linkedin="#"][/thb_team_parent][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	return $template_list;
}